export const errorKeys = {
  general: {
    Resource_Does_Not_Exist: 'Resource_Does_Not_Exist',
    Object_Is_Connected_With_Another_And_Can_Not_Be_Deleted: 'Object_Is_Connected_With_Another_And_Can_Not_Be_Deleted',
  },
  login: {
    Invalid_Login_Or_Passcode: 'Invalid_Login_Or_Passcode',
    User_Passcode_Is_Not_Set: 'User_Passcode_Is_Not_Set',
    Wrong_Authentication_Token: 'Wrong_Authentication_Token',
    User_Not_Authenticated: 'User_Not_Authenticated',
    User_Not_Authorized: 'User_Not_Authorized',
    User_Is_Not_Active: 'User_Is_Not_Active',
    Account_Is_Locked_Out: 'Account_Is_Locked_Out',
    Invalid_Authentication_Type: 'Invalid_Authentication_Type',
    Invalid_Reset_Passcode_Token: 'Invalid_Reset_Passcode_Token',
    Refresh_Token_Expired: 'Refresh_Token_Expired',
  },
  users: {
    Invalid_Phone: 'Invalid_Phone',
    Phone_Too_Long: 'Phone_Too_Long',
    Invalid_Email: 'Invalid_Email',
    Email_Too_Long: 'Email_Too_Long',
    FirstName_Too_Long: 'FirstName_Too_Long',
    LastName_Too_Long: 'LastName_Too_Long',
    Invalid_Email_Or_Phone: 'Invalid_Email_Or_Phone',
    Invalid_Passcode: 'Invalid_Passcode',
    User_Already_Exists: 'User_Already_Exists',
    User_Does_Not_Exist: 'User_Does_Not_Exist',
    Invalid_User_Id: 'Invalid_User_Id',
    Invalid_FirstName: 'Invalid_FirstName',
    Invalid_LastName: 'Invalid_LastName',
    Invalid_JoiningDate: 'Invalid_JoiningDate',
    Activation_Failed_Passcode_Is_Not_Set: 'Activation_Failed_Passcode_Is_Not_Set',
  },
  announcements: {
    Announcements_With_Given_ValidFromDate_Already_Exists: 'Announcements_With_Given_ValidFromDate_Already_Exists',
    Announcements_Does_Not_Exist: 'Announcements_Does_Not_Exist',
    Title_Too_Long: 'Announcements_Title_Too_Long',
    Item_Content_Is_Required: 'Announcements_Item_Content_Is_Required',
    Item_Content_Too_Long: 'Announcements_Item_Content_Too_Long',
    Announcements_Without_ValidFromDate_Can_Not_Be_Published:
      'Announcements_Without_ValidFromDate_Can_Not_Be_Published',
    Cannot_Save_Published_Announcements_Without_ValidFromDate:
      'Cannot_Save_Published_Announcements_Without_ValidFromDate',
  },
  calendar: {
    Invalid_Start_Date: 'Invalid_Start_Date',
    Invalid_End_Date: 'Invalid_End_Date',
  },
  bulletin: {
    Title_Is_Required: 'Bulletin_Title_Is_Required',
    Title_Too_Long: 'Bulletin_Title_Too_Long',
    Title_Must_Be_A_String: 'Bulletin_Title_Must_Be_A_String',
    Date_Is_Required: 'Bulletin_Date_Is_Required',
    Number_Is_Required: 'Bulletin_Number_Is_Required',
    Section_Title_Too_Long: 'Bulletin_Section_Title_Too_Long',
    Section_Content_Too_Long: 'Bulletin_Section_Content_Too_Long',
    Bulletin_Does_Not_Exist: 'Bulletin_Does_Not_Exist',
    Bulletin_With_Given_Date_Already_Exists: 'Bulletin_With_Given_Date_Already_Exists',
    Min_Number_Greater_Than_Zero: 'Bulletin_Min_Number_Greater_Than_Zero',
    Introduction_Is_Required: 'Bulletin_Introduction_Is_Required',
    Tips_For_Work_Is_Required: 'Bulletin_Tips_For_Work_Is_Required',
    Daily_Prayer_Is_Required: 'Bulletin_Daily_Prayer_Is_Required',
    Bulletin_Must_Have_At_Least_One_Day: 'Bulletin_Must_Have_At_Least_One_Day',
    Day_Date_Is_Required: 'Bulletin_Day_Date_Is_Required',
    Day_Title_Is_Required: 'Bulletin_Day_Title_Is_Required',
    Day_Must_Have_At_Least_One_Section: 'Bulletin_Day_Must_Have_At_Least_One_Section',
    Section_Type_Is_Required: 'Bulletin_Section_Type_Is_Required',
    Custom_Section_Title_Is_Required: 'Bulletin_Custom_Section_Title_Is_Required',
    Custom_Section_Content_Is_Required: 'Bulletin_Custom_Section_Content_Is_Required',
    Non_Custom_Section_Should_Not_Have_Title: 'Bulletin_Non_Custom_Section_Should_Not_Have_Title',
    Non_Custom_Section_Should_Not_Have_Content: 'Bulletin_Non_Custom_Section_Should_Not_Have_Content',
    Bulletin_Day_With_Given_Date_Already_Exists: 'Bulletin_Day_With_Given_Date_Already_Exists',
  },
  logs: {},
};
