export const errorKeys = {
  general: {
    Resource_Does_Not_Exist: 'Resource_Does_Not_Exist',
    Object_Is_Connected_With_Another_And_Can_Not_Be_Deleted: 'Object_Is_Connected_With_Another_And_Can_Not_Be_Deleted',
  },
  login: {
    Invalid_Login_Or_Passcode: 'Invalid_Login_Or_Passcode',
    User_Passcode_Is_Not_Set: 'User_Passcode_Is_Not_Set',
    Wrong_Authentication_Token: 'Wrong_Authentication_Token',
    User_Not_Authenticated: 'User_Not_Authenticated',
    User_Not_Authorized: 'User_Not_Authorized',
    User_Is_Not_Active: 'User_Is_Not_Active',
    Account_Is_Locked_Out: 'Account_Is_Locked_Out',
    Invalid_Authentication_Type: 'Invalid_Authentication_Type',
    Invalid_Reset_Passcode_Token: 'Invalid_Reset_Passcode_Token',
    Refresh_Token_Expired: 'Refresh_Token_Expired',
  },
  users: {
    Invalid_Phone: 'Invalid_Phone',
    Phone_Too_Long: 'Phone_Too_Long',
    Invalid_Email: 'Invalid_Email',
    Email_Too_Long: 'Email_Too_Long',
    FirstName_Too_Long: 'FirstName_Too_Long',
    LastName_Too_Long: 'LastName_Too_Long',
    Invalid_Email_Or_Phone: 'Invalid_Email_Or_Phone',
    Invalid_Passcode: 'Invalid_Passcode',
    User_Already_Exists: 'User_Already_Exists',
    User_Does_Not_Exist: 'User_Does_Not_Exist',
    Invalid_User_Id: 'Invalid_User_Id',
    Invalid_FirstName: 'Invalid_FirstName',
    Invalid_LastName: 'Invalid_LastName',
    Invalid_JoiningDate: 'Invalid_JoiningDate',
    Activation_Failed_Passcode_Is_Not_Set: 'Activation_Failed_Passcode_Is_Not_Set',
  },
  announcements: {
    Announcements_With_Given_ValidFromDate_Already_Exists: 'Announcements_With_Given_ValidFromDate_Already_Exists',
    Announcements_Does_Not_Exist: 'Announcements_Does_Not_Exist',
    Title_Too_Long: 'Announcements_Title_Too_Long',
    Item_Content_Is_Required: 'Announcements_Item_Content_Is_Required',
    Item_Content_Too_Long: 'Announcements_Item_Content_Too_Long',
    Announcements_Without_ValidFromDate_Can_Not_Be_Published: 'Announcements_Without_ValidFromDate_Can_Not_Be_Published',
    Cannot_Save_Published_Announcements_Without_ValidFromDate: 'Cannot_Save_Published_Announcements_Without_ValidFromDate',
  },
  calendar: {
    Invalid_Start_Date: 'Invalid_Start_Date',
    Invalid_End_Date: 'Invalid_End_Date',
  },
};
