import { config } from 'dotenv';
config({ path: `.env.${process.env.NODE_ENV ?? 'development'}.local` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const {
  NODE_ENV,
  PORT,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  SECRET_AUDIENCE,
  SECRET_ISSUER,
  REFRESH_TOKEN_EXPIRE_IN,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  BASE_PATH,
  CLIENT_APP_URL,
  SMTP_SERVICE_HOST,
  SMTP_SERVICE_PORT,
  SMTP_USER_NAME,
  SMTP_USER_PASSWORD,
  NOTIFICATIONS_EMAIL,
  REQ_RESET_PASSWORD_TITLE,
  RESET_PASSWORD_TOKEN_EXPIRE_IN,
  GOOGLE_API_CLIENT_ID,
  GOOGLE_API_CLIENT_SECRET,
  GOOGLE_API_REFRESH_TOKEN,
  GOOGLE_CALENDAR_ID,
} = process.env;
